use paijiu_data if exists paijiu_data;
ALTER TABLE game_history DROP COLUMN player_id;
ALTER TABLE game_history DROP COLUMN renshu;
ALTER TABLE game_history DROP COLUMN status;
ALTER TABLE game_history DROP COLUMN use_fangka;
ALTER TABLE game_history DROP COLUMN game_status;
ALTER TABLE game_history DROP COLUMN creat_time;
ALTER TABLE game_history DROP COLUMN room_num;
ALTER TABLE game_history ADD COLUMN location1  INT DEFAULT -1;
ALTER TABLE game_history ADD COLUMN location2  INT DEFAULT -1;
ALTER TABLE game_history ADD COLUMN location3  INT DEFAULT -1;
ALTER TABLE game_history ADD COLUMN location4  INT DEFAULT -1;
ALTER TABLE game_history ADD COLUMN score1  INT DEFAULT 0;
ALTER TABLE game_history ADD COLUMN score2  INT DEFAULT 0;
ALTER TABLE game_history ADD COLUMN score3  INT DEFAULT 0;
ALTER TABLE game_history ADD COLUMN score4  INT DEFAULT 0;
ALTER TABLE game_history ADD COLUMN renshu  INT DEFAULT 0;
ALTER TABLE game_history ADD COLUMN status  INT DEFAULT 0;
ALTER TABLE game_history ADD COLUMN game_type  INT DEFAULT 0;
ALTER TABLE game_history ADD COLUMN creat_time  BIGINT;
ALTER TABLE game_history ADD COLUMN room_num   VARCHAR(6);
